DROP TABLE GROUPS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_GROUPS;

CREATE TABLE GROUPS(
	GROUPS_SEQ NUMBER(8) PRIMARY KEY,
	CATEGORY VARCHAR2(50) NOT NULL,
	LOCATION VARCHAR2(200) NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	FILENAME VARCHAR2(50) NOT NULL,
	NEWFILENAME VARCHAR2(50) NOT NULL,
	REGIDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_GROUPS
START WITH 1 INCREMENT BY 1;

-- MEMBER정보 만들기전까지는 이용불가
ALTER TABLE GROUPS
ADD CONSTRAINT FK_GROUPS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

select * from GROUPS;

