CREATE TABLE BBS( -- 저장할공간 만들기
    BBS_SEQ NUMBER(5) NOT NULL,		-- 작성글 순서
    GROUPS_SEQ NUMBER(5) NOT NULL,	
    ID VARCHAR2(50) NOT NULL,		-- 작성자
    REF NUMBER(10) NOT NULL,		
    STEP NUMBER(10) NOT NULL,
    DEPTH NUMBER(10) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,	-- 글 제목
    CONTENT VARCHAR2(2000) NOT NULL,--글 내용
    TYPE VARCHAR2(50)NOT NULL,	-- (자유글/공지사항)	
    WDATE DATE NOT NULL,			--작성날짜
    DEL NUMBER(1),					-- 글 삭제
    CONSTRAINT PK_BBS PRIMARY KEY(BBS_SEQ)
);


DROP TABLE BBS
CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE SEQ_BBS;

-- *group 가져오면 실행가능
ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_SEQ FOREIGN KEY(GROUPS_SEQ)
REFERENCES GROUPS(GROUPS_SEQ);

ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE BBS DROP CONSTRAINT GROUPS_SEQ;

SELECT * FROM  BBS;


SELECT BBS_SEQ, GROUPS_SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, TYPE, WDATE, DEL
FROM (SELECT ROW_NUMBER()OVER(ORDER BY REF DESC, STEP ASC) AS RNUM,
		BBS_SEQ, GROUPS_SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, TYPE, WDATE, DEL
		FROM BBS
		WHERE TYPE=''
		ORDER BY REF DESC, STEP ASC)
WHERE RNUM >= 1 AND RNUM <= 5;
