CREATE TABLE GROUP_MEM(
    GROUP_MEM_SEQ NUMBER(5) PRIMARY KEY,
    GROUPS_SEQ NUMBER(5) NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    JOINDATE DATE NOT NULL,
    DEL NUMBER(1)
);

CREATE SEQUENCE SEQ_GROUP_MEM
START WITH 1
INCREMENT BY 1;

DROP TABLE GROUP_MEM
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_GROUP_MEM;

DELETE FROM GROUP_MEM;

ALTER TABLE GROUP_MEM
ADD CONSTRAINT FK_MEM_SEQ FOREIGN KEY(GROUPS_SEQ)
REFERENCES GROUPS(GROUPS_SEQ);

ALTER TABLE GROUP_MEM
ADD CONSTRAINT FK_MEM_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE GROUP_MEM DROP CONSTRAINT GROUPS_SEQ;

SELECT * FROM  GROUP_MEM;
DELETE FROM GROUP_MEM;

-- MEMBER과 GROUP_MEM 회원 연동하기
SELECT GROUP_MEM_SEQ, GROUPS_SEQ, ID, NAME, JOINDATE, DEL
FROM GROUP_MEM
WHERE ID IN(SELECT ID
			FROM MEMBER
			WHERE GROUP_AUTH = 0)
	AND GROUPS_SEQ=?;
	
	
SELECT MEM_SEQ, ID, PWD, NAME, BIRTH, GENDER, PHONE, EMAIL, CATEGORY, LOCATION, AUTH, GROUP_AUTH, JOINDATE
FROM MEMBER
WHERE ID IN(SELECT ID
			FROM GROUP_MEM
			WHERE GROUPS_SEQ=2)