CREATE TABLE MEETING_MEM(
    MEETING_MEM_SEQ NUMBER(5) NOT NULL,
    MEETING_SEQ NUMBER(5) NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    JOINDATE DATE NOT NULL,
    DEL NUMBER(1)
);

CREATE SEQUENCE MEETING_MEM_SEQ
START WITH 1
INCREMENT BY 1;

DROP TABLE MEETING_MEM
CASCADE CONSTRAINTS;

DROP SEQUENCE MEETING_MEM_SEQ;

ALTER TABLE MEETING_MEM
ADD CONSTRAINT FK_MEETING_MEM_SEQ FOREIGN KEY(MEETING_SEQ)
REFERENCES MEETING(MEETING_SEQ);

ALTER TABLE MEETING_MEM
ADD CONSTRAINT FK_MEETING_MEM_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE MEETING_MEM DROP CONSTRAINT CALENDAR_SEQ;

SELECT * FROM  MEETING_MEM;
DELETE FROM MEETING_MEM;

SELECT COUNT(distinct(ID))
FROM MEETING_MEM
WHERE MEETING_SEQ=2;